In [16]:
import numpy as np
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC

iris = datasets.load_iris()
X = iris["data"][:, (2,3)]  # petal length, petal width
y = (iris["target"] == 2).astype(np.float64)  # Iris-Virginica

svm_clf = Pipeline((
    ("scaler", StandardScaler()),
    ("linear_svc", LinearSVC(C=1, loss="hinge")),
))

svm_clf.fit(X, y)


Pipeline(memory=None,
     steps=[('scaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('linear_svc', LinearSVC(C=1, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='hinge', max_iter=1000, multi_class='ovr',
     penalty='l2', random_state=None, tol=0.0001, verbose=0))])

In [17]:
svm_clf.predict([[6.5, 1.7]])

array([ 1.])

In [19]:
from sklearn.datasets import make_moons
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures

polynomial_svm_clf = Pipeline((
    ("poly_features", PolynomialFeatures(degree=3)),
    ("scaler", StandardScaler()),
    ("svm_clf", LinearSVC(C=10, loss="hinge"))  
))

polynomial_svm_clf.fit(X, y)

Pipeline(memory=None,
     steps=[('poly_features', PolynomialFeatures(degree=3, include_bias=True, interaction_only=False)), ('scaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('svm_clf', LinearSVC(C=10, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='hinge', max_iter=1000, multi_class='ovr',
     penalty='l2', random_state=None, tol=0.0001, verbose=0))])

In [20]:
polynomial_svm_clf.predict([[6.5, 1.7]])

array([ 1.])

In [21]:
from sklearn.svm import SVC
poly_kernel_svm_clf = Pipeline((
    ("scaler", StandardScaler()),
    ("svm_clf", SVC(kernel="poly", degree=3, coef0=1, C=5))
))
poly_kernel_svm_clf.fit(X, y)

Pipeline(memory=None,
     steps=[('scaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('svm_clf', SVC(C=5, cache_size=200, class_weight=None, coef0=1,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False))])

In [22]:
poly_kernel_svm_clf.predict([[6.5, 1.7]])

array([ 1.])

In [27]:
rbf_kernel_svm_clf = Pipeline((
    ("scaler", StandardScaler()),
    ("svm_clf", SVC(kernel="rbf", gamma=5, C=1))
))

rbf_kernel_svm_clf.fit(X, y)

Pipeline(memory=None,
     steps=[('scaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('svm_clf', SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=5, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False))])

In [29]:
rbf_kernel_svm_clf.predict([[6.5, 1.2]])

array([ 1.])

In [1]:
from sklearn.datasets import fetch_mldata
import numpy as np

mnist = fetch_mldata('MNIST original')
X,y=mnist["data"],mnist["target"]
X_train, X_test, y_train, y_test = X[:60000], X[60000:], y[:60000], y[60000:]
shuffle_index = np.random.permutation(60000)
X_train, y_train = X_train[shuffle_index], y_train[shuffle_index]

HTTPError: HTTP Error 500: Internal Server Error

In [ ]:
X.shape

In [3]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC

svm_clf = Pipeline((
    ("scaler", StandardScaler()),
    ("linear_svc", LinearSVC(C=1, loss="hinge")),
))

svm_clf.fit(X_train, y_train)

C:\Users\Boyuan.Feng\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype uint8 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


Pipeline(memory=None,
     steps=[('scaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('linear_svc', LinearSVC(C=1, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='hinge', max_iter=1000, multi_class='ovr',
     penalty='l2', random_state=None, tol=0.0001, verbose=0))])

In [5]:
from sklearn.metrics import f1_score

y_test_predict = svm_clf.predict(X_test)
f1_score(y_test, y_test_predict, average="macro")

C:\Users\Boyuan.Feng\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype uint8 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


0.91700517921756008

In [15]:
import pandas as pd
import os

csv_path = os.path.join("datasets", "housing", "housing.csv")
housing = pd.read_csv("C:\\Boyuan\\MyPython\\HandsOnML\\datasets\\housing\\housing.csv")
housing.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
longitude             20640 non-null float64
latitude              20640 non-null float64
housing_median_age    20640 non-null float64
total_rooms           20640 non-null float64
total_bedrooms        20433 non-null float64
population            20640 non-null float64
households            20640 non-null float64
median_income         20640 non-null float64
median_house_value    20640 non-null float64
ocean_proximity       20640 non-null object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [17]:
import numpy as np
from sklearn.model_selection import StratifiedShuffleSplit

housing["income_cat"] = np.ceil(housing["median_income"] / 1.5)
housing["income_cat"].where(housing["income_cat"] < 5, 5.0, inplace=True)

split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(housing, housing["income_cat"]):
    strat_train_set = housing.loc[train_index]
    strat_test_set = housing.loc[test_index]

In [87]:
train_index

array([17606, 18632, 14650, ..., 13908, 11159, 15775], dtype=int64)

In [88]:
test_index

array([ 5241, 10970, 20351, ...,  4019, 12107,  2398], dtype=int64)

In [83]:
strat_train_set.iloc[2]

longitude                 -117.2
latitude                   32.77
housing_median_age            31
total_rooms                 1952
total_bedrooms               471
population                   936
households                   462
median_income             2.8621
median_house_value        196900
ocean_proximity       NEAR OCEAN
income_cat                     2
Name: 14650, dtype: object

In [21]:
housing_train = strat_train_set.drop("median_house_value",axis=1)
housing_train_labels = strat_train_set["median_house_value"].copy()
housing_test = strat_test_set.drop("median_house_value",axis=1)
housing_test_labels = strat_test_set["median_house_value"].copy()

In [33]:
housing_train.iloc[2]

longitude                 -117.2
latitude                   32.77
housing_median_age            31
total_rooms                 1952
total_bedrooms               471
population                   936
households                   462
median_income             2.8621
ocean_proximity       NEAR OCEAN
income_cat                     2
Name: 14650, dtype: object

In [84]:
housing_train_labels.iloc[2]

196900.0

In [36]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import LabelBinarizer
class LabelBinarizer_new(BaseEstimator, TransformerMixin):       
    def fit(self, X, y = None):
        self.encoder = LabelBinarizer();
        self.encoder.fit(X)
        return self
    def transform(self, X, y = None):
        result = self.encoder.transform(X)
        return result

In [37]:
housing_num = housing_train.drop('ocean_proximity', axis=1)

In [39]:
from sklearn.base import BaseEstimator, TransformerMixin

# Create a class to select numerical or categorical columns 
# since Scikit-Learn doesn't handle DataFrames yet
class DataFrameSelector(BaseEstimator, TransformerMixin):
    def __init__(self, attribute_names):
        self.attribute_names = attribute_names
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[self.attribute_names].values

In [41]:
from sklearn.base import BaseEstimator, TransformerMixin

# column index
rooms_ix, bedrooms_ix, population_ix, household_ix = 3, 4, 5, 6

class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def __init__(self, add_bedrooms_per_room = True): # no *args or **kargs
        self.add_bedrooms_per_room = add_bedrooms_per_room
    def fit(self, X, y=None):
        return self  # nothing else to do
    def transform(self, X, y=None):
        rooms_per_household = X[:, rooms_ix] / X[:, household_ix]
        population_per_household = X[:, population_ix] / X[:, household_ix]
        if self.add_bedrooms_per_room:
            bedrooms_per_room = X[:, bedrooms_ix] / X[:, rooms_ix]
            return np.c_[X, rooms_per_household, population_per_household,
                         bedrooms_per_room]
        else:
            return np.c_[X, rooms_per_household, population_per_household]

In [42]:
from sklearn.pipeline import FeatureUnion
from sklearn.preprocessing import Imputer

num_attribs = list(housing_num)
cat_attribs = ["ocean_proximity"]

num_pipeline = Pipeline([
        ('selector', DataFrameSelector(num_attribs)),
        ('imputer', Imputer(strategy="median")),
        ('attribs_adder', CombinedAttributesAdder()),
        ('std_scaler', StandardScaler()),
    ])

cat_pipeline = Pipeline([
        ('selector', DataFrameSelector(cat_attribs)),
        ('label_binarizer', LabelBinarizer_new()),
    ])

full_pipeline = FeatureUnion(transformer_list=[
        ("num_pipeline", num_pipeline),
        ("cat_pipeline", cat_pipeline),
    ])

In [45]:
train_prepared = full_pipeline.fit_transform(housing_train)

In [124]:
from sklearn.svm import LinearSVR
from sklearn.metrics import mean_squared_error

lin_svr = LinearSVR(random_state=42, C=1000.0 , epsilon=3)
lin_svr.fit(train_prepared, housing_train_labels)

y_train_pred_svr = lin_svr.predict(train_prepared)
mse_train_svr = mean_squared_error(housing_train_labels, y_train_pred_svr)
mse_train_svr

4945643051.633666

In [125]:
lin_reg = LinearRegression()
lin_reg.fit(train_prepared, housing_train_labels)

y_train_pred_reg = lin_reg.predict(train_prepared)
mse_train_reg = mean_squared_error(housing_train_labels, y_train_pred_reg)
mse_train_reg

4675365301.7407656

In [127]:
test_prepared = full_pipeline.transform(housing_test)

In [128]:
housing_test_predict_svr = lin_svr.predict(test_prepared)
mse_test_svr = mean_squared_error(housing_test_labels, housing_test_predict_svr)
mse_test_svr

4698136796.7126808

In [129]:
housing_test_predict_reg = lin_reg.predict(test_prepared)
mse_test_reg = mean_squared_error(housing_test_labels, housing_test_predict_reg)
mse_test_reg

4454409471.2266951

In [130]:
housing_test_predict_svr[2]

204694.60929518062

In [131]:
housing_test_labels.iloc[2]

218200.0

In [68]:
housing_test_predict

array([ 23860.67278738,  23822.73652749,  23808.26732871, ...,
        23810.26021475,  21816.62189311,  21710.54834327])

In [58]:
from sklearn.metrics import mean_squared_error

lin_mse = mean_squared_error(housing_test_labels, housing_test_predict)
lin_rmse = np.sqrt(lin_mse)
lin_rmse

216947.08076503192

In [144]:
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error

svm_poly_reg = SVR(kernel="poly", degree=2, C=50000, epsilon=3)
svm_poly_reg.fit(train_prepared, housing_train_labels)

y_train_pred_svr_poly = svm_poly_reg.predict(train_prepared)
mse_train_svr_poly = mean_squared_error(housing_train_labels, y_train_pred_svr_poly)
mse_train_svr_poly

4131286827.0121336

In [146]:
housing_test_predict_svr_poly = svm_poly_reg.predict(test_prepared)
mse_test_svr_poly = mean_squared_error(housing_test_labels, housing_test_predict_svr_poly)
mse_test_svr_poly

4047292890.8403707